### ISSUE TITLE
Change pyiron_atomistics to broken

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/pyiron_atomistics-feedstock#4]
Hi @conda-forge/core,

 Please move my package from ``main`` to ``broken`` on the conda-forge channel on anaconda.org
 because: We merged the pyiron packages to one big package, meaning: 

- pyiron_base
- pyiron_atomistics
- pyiron_dft
- pyiron_example_job
- pyiron_lammps 
- pyiron_vasp 

Are now all included in pyiron, before these were individual packages. 

best, 

Jan

**Comment by ocefpaf** [comment]
That is not really a reason to move packages to broken and may break users experiences using the old ones. Do you really want to do this? I'd rather if we had a new releases of each one of the individual pieces with a deprecation warning request users to move to the consolidated pacakge.

**Comment by jan-janssen** [comment]
@ocefpaf my idea was to delete the packages as our user base is currently still very limited and it might be confusing for new users to find the outdated packages.

**Comment by ocefpaf** [comment]
It is still preferred to the deprecation, however, to make things simpler to you, I just moved those to the broken label.

**Comment by jan-janssen** [comment]
thanks a lot.
